[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
messages = { path = "../services/messages" }
axum = "0.8.3"
prometheus = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
