[package]
name = "templates"
version = "0.1.0"
edition = "2021"

[dependencies]
messages = { path = "../services/messages" }
shared = { path = "../shared" }
maud = { version = "*", features = ["axum"] }
axum = { workspace = true }
